# typed: false
# frozen_string_literal: true

# Formula for Oh My Agentic Score (omas)
# Install: brew install HwangTaehyun/tap/oh-my-agentic-score
#
# This formula installs via pipx for clean isolated environment.
# Resource blocks are auto-generated by the update-formula workflow.

class OhMyAgenticScore < Formula
  include Language::Python::Virtualenv

  desc "Measure and visualize agentic coding performance"
  homepage "https://github.com/HwangTaehyun/oh-my-agentic-score"
  url "https://files.pythonhosted.org/packages/source/o/oh-my-agentic-score/oh_my_agentic_score-0.1.0.tar.gz"
  sha256 "PLACEHOLDER_SHA256"
  license "MIT"

  depends_on "python@3.13"

  # ============================================================
  # Resource blocks (dependencies)
  # Auto-generated by: poet -f oh-my-agentic-score
  # Re-generate after each release with the GitHub Actions workflow
  # or manually with:
  #   python3 -m venv /tmp/poet-env
  #   source /tmp/poet-env/bin/activate
  #   pip install oh-my-agentic-score homebrew-pypi-poet
  #   poet -f oh-my-agentic-score
  # ============================================================

  # PLACEHOLDER: Run `poet -f oh-my-agentic-score` after PyPI publish
  # to generate all resource blocks. Example:
  #
  # resource "click" do
  #   url "https://files.pythonhosted.org/packages/source/c/click/click-8.1.8.tar.gz"
  #   sha256 "..."
  # end

  def install
    virtualenv_install_with_resources
  end

  test do
    assert_match "Oh My Agentic Score", shell_output("#{bin}/omas --help")
  end
end
