"""Tests for human message filtering (Bug #3 fix)."""
import pytest
from omas.parser.session_parser import _extract_human_text, _is_human_message


def _make_user_record(content, user_type="external"):
    return {"type": "user", "userType": user_type, "message": {"content": content}}


class TestAutomatedPatternFiltering:
    """Automated messages should NOT be counted as human."""

    @pytest.mark.parametrize("content", [
        "gitStatus: main branch\nM src/file.py",
        "currentDate: 2026-03-05",
        "<system-reminder>some reminder</system-reminder>",
        "This session is being continued from a previous conversation that ran out of context.",
        "<observed_from_primary_session>data here",
        "<local-command-caveat>Caveat: blah",
        "task-notification: task completed",
        "<task-id>abc123</task-id>",
        "<teammate-message from='agent1'>hello</teammate-message>",
        "PreToolUse hook blocked the call",
        "Hook feedback: success",
        "Hook says: approved",
        "Current branch: main",
        "This is the git status at the start",
        "Environment: darwin arm64",
        "<user-prompt-submit-hook>data</user-prompt-submit-hook>",
        "<available-deferred-tools>tool list here",
        "Caveat: The messages below were generated by the user",
        "<command-name>some-command</command-name>",
        "Stop hook feedback: blocked",
        "Stop hook blocking: reason",
    ])
    def test_automated_patterns_filtered(self, content):
        record = _make_user_record(content)
        assert _extract_human_text(record) is None

    @pytest.mark.parametrize("content", [
        "Fix the login bug please",
        "Can you refactor this function?",
        "bump",
        "yes",
        "/commit",
    ])
    def test_genuine_human_messages_pass(self, content):
        record = _make_user_record(content)
        assert _extract_human_text(record) is not None


class TestMinimumLength:
    """Very short messages should be filtered."""

    @pytest.mark.parametrize("content", [
        "",
        " ",
        "y",
        "ok",  # 2 chars, below 3
    ])
    def test_short_messages_filtered(self, content):
        record = _make_user_record(content)
        assert _extract_human_text(record) is None

    def test_three_char_message_passes(self):
        record = _make_user_record("yes")
        assert _extract_human_text(record) is not None

    def test_non_external_user_filtered(self):
        record = _make_user_record("hello world", user_type="internal")
        assert _extract_human_text(record) is None


class TestListContent:
    """Test list-format content filtering."""

    def test_list_with_only_tool_results(self):
        record = _make_user_record([
            {"type": "tool_result", "content": "ok"}
        ])
        assert _extract_human_text(record) is None

    def test_list_with_human_text(self):
        record = _make_user_record([
            {"type": "text", "text": "Fix the bug please"}
        ])
        assert _extract_human_text(record) is not None

    def test_list_with_automated_text(self):
        record = _make_user_record([
            {"type": "text", "text": "<system-reminder>blah</system-reminder>"}
        ])
        assert _extract_human_text(record) is None

    def test_list_with_short_text(self):
        record = _make_user_record([
            {"type": "text", "text": "y"}
        ])
        assert _extract_human_text(record) is None
